FROM node:24-bullseye

#RUN mkdir -p /app
RUN mkdir -p /app/node_modules/.cache
RUN chown -R node:node /app

WORKDIR /app

# Copy package files first for better caching
COPY --chown=node:node ./package.json ./

#RUN mkdir -p /app/node_modules/.cache

# Configure npm for potential network issues
RUN npm config set registry https://registry.npmjs.org/ && \
    npm config set strict-ssl false

# Copy remaining files
COPY --chown=node:node . .

# Change ownership of the app directory
#RUN chown -R node:node /app

# Install dependencies from package.json
RUN npm install


# Set environment variable
ENV NODE_OPTIONS=--openssl-legacy-provider

# Switch to non-root user
USER node

# Start the application
CMD ["sh", "-c", "NODE_OPTIONS=--openssl-legacy-provider npm start"]
